/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hongkl_cainiaotuan_NdkUtil */

#ifndef _Included_com_example_hongkl_cainiaotuan_NdkUtil
#define _Included_com_example_hongkl_cainiaotuan_NdkUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hongkl_cainiaotuan_NdkUtil
 * Method:    getStringFromNative
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_hongkl_cainiaotuan_NdkUtil_getStringFromNative
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
