/* DO NOT EDIT THIS FILE - it is machine generated */

#include <jni.h>


JNIEXPORT jstring JNICALL Java_com_example_hongkl_cainiaotuan_NdkUtil_getStringFromNative(JNIEnv *env, jobject jObj){
  return (*env)->NewStringUTF(env,"HelloFrom JNI!");
}


